### PR TITLE
Include `ServerClaim` UID in `Node` ProviderID

### LINKED ISSUE #17: Set Correct `ProviderID` Format in `cloud-provider-metal`
### Problem Statement

Currently, the `ProviderID` in `Node` objects for the `cloud-provider-metal` is set in the following format:

- **Current format:**  
  `providerID: metal://<namespace>/<serverclaim-name>`

This format is inadequate for uniquely identifying nodes, particularly in scenarios where namespace and server claim names might be duplicated across clusters. 

### Proposed Solutions

We need to modify the `ProviderID` format to ensure unique identification of nodes. Below are the alternative formats proposed:

1. **Option 1:**  
   `providerID: metal://<namespace>/<serverclaim-name>/<serverclaim-uid>`
   
   - **Pros:** Uniquely identifies each `serverclaim` by including its UID, even within the same namespace.
   - **Cons:** Increases the length of the `ProviderID`.

2. **Option 2:**  
   `providerID: metal://<cluster-identity>/<namespace>/<serverclaim-name>`
   
   - **Pros:** Ensures uniqueness across clusters by incorporating a cluster-wide identifier.
   - **Cons:** Does not account for multiple claims within the same namespace that might have the same name.

3. **Option 3:**  
   `providerID: metal://<cluster-identity>/<namespace>/<serverclaim-name>/<serverclaim-uid>`
   
   - **Pros:** Combines both cluster identity and the server claim's UID for maximum uniqueness.
   - **Cons:** Longest format, may lead to issues if there's a character limit on `ProviderID`.

### Recommended Action

- **Primary Recommendation:** Adopt **Option 3** (`providerID: metal://<cluster-identity>/<namespace>/<serverclaim-name>/<serverclaim-uid>`) as it offers the most comprehensive solution for unique node identification across different clusters and namespaces.
  
### Definition of Done

- Update the `ProviderID` format in the `cloud-provider-metal` implementation to the agreed-upon format.
- Ensure backward compatibility with existing `ProviderID` formats or provide a clear migration path.
- Update documentation to reflect the new `ProviderID` format and its usage.
- Conduct thorough testing to verify that the new format correctly identifies nodes without introducing any regressions or new issues.

### PR DESCRIPTION
**Pull request by afritzler**
# Proposed Changes

Include `ServerClaim` UID in `Node` ProviderID.

```
providerID: metal://<namespace>/<serverclaim-name>/<serverclaim-uid>
```

Fixes #17

### CODE REVIEW

File: pkg/cloudprovider/metal/instances_v2_test.go [hunk 1]
```diff
@@ -207,7 +207,7 @@ var _ = Describe("InstancesV2", func() {
 				Name: "foo",
 			},
 			Spec: corev1.NodeSpec{
-				ProviderID: getProviderID(ns.Name, "bar"),
+				ProviderID: fmt.Sprintf("%s://%s/%s/%s", ProviderName, ns.Name, "foo", "bar"),
```
Comment (Nuckal777) [inline pkg/cloudprovider/metal/instances_v2_test.go:210]: Nitpick: `fmt.Sprintf("%s://%s/foo/bar", ProviderName, ns.Name)`

**Review by Nuckal777 — APPROVED** [review]

File: pkg/cloudprovider/metal/instances_v2_test.go (hunk 1 above)
Comment (afritzler) [reply pkg/cloudprovider/metal/instances_v2_test.go:210]: No, that is actually is a good catch.

Comment (afritzler) [reply pkg/cloudprovider/metal/instances_v2_test.go]: Fixed that one.
